### ISSUE TITLE
Demo snippet doesn't show demo source on IE11

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-demo-helpers#9]

**Comment by samiheikki** [comment]
Especially when you are using another `<template>` inside the snippet.

**Comment by samiheikki** [comment]
This would be quite impossible/hard to fix as the problem is in IE11's support for Shady DOM.
More info: https://github.com/webcomponents/shadydom/issues/117

**Comment by web-padawan** [comment]
Fixed in webcomponents/template#33 which has been shipped in `webcomponentsjs` v1.1.1
I have tried installing different versions of polyfill and I was able to confirm the fix.
See the screenshots of the demo pages for dialog containing nested templates:

Before (webcomponentsjs v1.1.0):
<img width="308" alt="screen shot 2018-03-22 at 22 26 52" src="https://user-images.githubusercontent.com/10589913/37796679-81ad2eec-2e20-11e8-885e-f0e8ba6284f4.png">

After (webcomponentsjs v1.1.1):
<img width="567" alt="screen shot 2018-03-22 at 22 27 13" src="https://user-images.githubusercontent.com/10589913/37796698-8b931df4-2e20-11e8-80d4-31347f8bb8cf.png">

We probably should depend on that version explicitly.
